version: '3'

services:
  data-service:
    build: ./data-service
    networks:
      - backend
    depends_on:
      - kafka
      - mysql-db
    environment:
      KAFKA_BROKER: kafka:9092

  api-service:
    build: ./api-service
    networks:
      - backend
    ports:
      - "8080:5000"
    depends_on:
      - kafka
      - data-service
    environment:
      KAFKA_BROKER: kafka:9092

  kafka:
    image: wurstmeister/kafka
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - backend

  zookeeper:
    image: wurstmeister/zookeeper
    networks:
      - backend

  mysql-db:
    image: mysql:latest
    networks:
      - backend
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: restaurant_reviews

networks:
  backend:
    driver: bridge
    internal: true
volumes:
  mysql-data: